### ISSUE TITLE
Some questions about test dataset

### ISSUE THREAD

**Issue by hxwork** [jiahaowork/idam#1]
Dear authors,

Thank you for making the codes public. I am very intrested about your works, and I have some questions about your codes:
1. I found that in PRNet's code, transformations of test data are fixed in this way:
```Python
if self.partition != 'train':
    np.random.seed(item)
```
But I am fail to find these codes in your codes. So are the transformations of test data fixed?  

2. You said that you used GNN as feature extractor, but the codes show that it is different from the GNN used in PRNet, in your codes, GNN is in this way:
```Python
class GNN(nn.Module):
    def __init__(self, emb_dims=64):
        super(GNN, self).__init__()
        self.propogate1 = Propagate(3, 64)
        self.propogate2 = Propagate(64, 64)
        self.propogate3 = Propagate(64, 64)
        self.propogate4 = Propagate(64, 64)
        self.propogate5 = Propagate(64, emb_dims)

    def forward(self, x):
        nn_idx = knn(x, k=12)

        x = self.propogate1(x, nn_idx)
        x = self.propogate2(x, nn_idx)
        x = self.propogate3(x, nn_idx)
        x = self.propogate4(x, nn_idx)
        x = self.propogate5(x, nn_idx)

        return x
```
But in this way, the idices will be fixed at first and not changed, and they are calculated by the Euclidean distance between coordinate points, instead of the L1 or L2 distance of the features. I think it is more like a variant of PointNet, not GNN.

I will be very appreciate if you can answer my doubts.

**Comment by jiahaoli95** [comment]
Hello,

Thanks for your interest!

1. It's been a long time ago and I do not remember every detail of the code. The data.py file is borrowed from DCP and PRNet, but is modified many times so it may not be exactly like the original. If you want to check if the transformation is fixed, you can print out immediate results of the first entry of the dataset to see if it changes every time.

2. PRNet uses DGCNN, which computes distance in feature space, so it is dynamic. GNN is a very general term, and covers a lot of architectures. I used a very naive version of it. The DGCNN paper lists some GNN variants, if you are interested.

Best,
Jiahao

**Comment by hxwork** [comment]
Thank you for your reply. Do you have any pre-trained checkpoints for unseen shapes in ModelNet40 with Gaussian noise?

**Comment by jiahaoli95** [comment]
Sorry we do not. But training a new one should be very quick.

**Comment by hxwork** [comment]
OK, thank you again for your prompt reply!

**Comment by OVEYA123** [comment]
Dear authors,
Why does the use of other features to embed the network make a big difference between the training results and the test results? such as  a pointnet or DGCNN. 
The result of using the author's GNN will be normal.

**Comment by jiahaoli95** [comment]
> Dear authors,
> Why does the use of other features to embed the network make a big difference between the training results and the test results? such as  a pointnet or DGCNN. 
> The result of using the author's GNN will be normal.  

I am not sure about that, I have not tried any larger network. Is it possible that the network is over fitting the dataset? Maybe you can reduce the number of parameters and try again.
